"""Main-text tables assembled from the appendix tables that
make_paper_tables.py writes, so a rerun of the grid regenerates them too.

  tab_grid_main.tex     default encoder (raw, corrected, gain, N50) + best encoder per collection
  tab_alternatives.tex  every alternative on the default encoder, columns = collections

Reads  appendix/tab_grid_full.tex, tab_baselines.tex, tab_adapters.tex, tab_lora.tex
Writes appendix/tab_grid_main.tex, appendix/tab_alternatives.tex
Usage  python analysis\\make_main_tables.py [--appendix appendix] [--default SigLIP2]
"""
from __future__ import annotations

import argparse
from pathlib import Path

CASE_ROWS = ["Duluth", "Popocat\\'epetl"]      # webcam collections of the case study; filled by hand until their runs exist
LORA_ENC = "CLIP ViT-L/14"


def rows(path: Path, n: int):
    out = []
    for line in open(path, encoding="utf-8"):
        if "&" not in line or "\\\\" not in line:
            continue
        c = [x.strip() for x in line.replace("\\\\", "").split("&")]
        if len(c) == n and c[0] and not c[0].startswith("\\") and c[0] != "Collection":
            out.append(c)
    return out


def f(x: str) -> float:
    return float(x.replace("$", "").replace("−", "-"))


def sg(v: float) -> str:
    return ("$-$" if v < 0 else "+") + f"{abs(v):.3f}"[1:]      # +.281 / $-$.048


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--appendix", default="appendix")
    ap.add_argument("--default", default="SigLIP2")
    a = ap.parse_args()
    A = Path(a.appendix); D = a.default
    grid = rows(A / "tab_grid_full.tex", 12)
    base = {(c[0], c[1]): c for c in rows(A / "tab_baselines.tex", 9)}
    adap = {(c[0], c[1]): c for c in rows(A / "tab_adapters.tex", 8)}
    lora = {c[0]: c for c in rows(A / "tab_lora.tex", 10) if c[1].replace(",", "").isdigit() and int(c[1].replace(",", "")) > 1000}

    by = {}
    for c in grid:
        by.setdefault(c[0], []).append(c)
    dflt = {ds: [c for c in L if c[1] == D][0] for ds, L in by.items()}
    order = sorted(by, key=lambda ds: -f(dflt[ds][8]))

    # ── tab_grid_main ──
    L = [r"\begin{table}[t]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{4pt}",
         r"\caption{\textbf{The gap and its repair, per collection.} Left: the default",
         r"encoder (" + D + r"), raw and corrected \Rk{50}, the two-map gain, and the",
         r"near-miss mass $N_{50}$ read from the training catalog before any map is",
         r"trained. Right: the encoder with the best corrected \Rk{50} on that",
         r"collection. Rows sorted by the default encoder's gain; COCO is the",
         r"web-register control. The last two rows are the webcam collections of",
         r"\S\ref{sec:casestudy}.}", r"\label{tab:grid_main}",
         r"\begin{tabular}{l rrrr l rr}", r"\toprule",
         r"& \multicolumn{4}{c}{" + D + r" (default)} & \multicolumn{3}{c}{best encoder after correction} \\",
         r"\cmidrule(lr){2-5}\cmidrule(lr){6-8}",
         r"Collection & raw & corrected & $\Delta$\Rk{50} & $N_{50}$ & encoder & raw & corrected \\", r"\midrule"]
    for ds in order:
        d = dflt[ds]; b = max(by[ds], key=lambda c: f(c[6]))
        L.append(f"{ds} & {d[4]} & {d[6]} & {'$-$' if f(d[8]) < 0 else '$+$'}{abs(f(d[8])):.3f} & {d[10]} & {b[1]} & {b[4]} & {b[6]} \\\\")
    L.append(r"\midrule")
    for r in CASE_ROWS:
        L.append(f"{r} & --- & --- & --- & --- & --- & --- & --- \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (A / "tab_grid_main.tex").write_text("% generated by analysis/make_main_tables.py\n" + "\n".join(L), encoding="utf-8")

    # ── tab_alternatives ──
    cols = order
    def row(name, vals, bold=None):
        cells = []
        for ds, v in zip(cols, vals):
            s = "---" if v is None else (sg(v) if isinstance(v, float) else v)
            if bold and ds in bold:
                s = r"\textbf{" + s + "}"
            cells.append(s)
        return name + " & " + " & ".join(cells) + r" \\"
    ours = {ds: f(base[(ds, D)][3]) for ds in cols}
    alt = {"CSLS ($k{=}10$)": [f(base[(ds, D)][4]) for ds in cols],
           "QB-Norm ($\\beta{=}20$)": [f(base[(ds, D)][5]) for ds in cols],
           "symmetric centering": [f(base[(ds, D)][6]) for ds in cols],
           "Liang $\\lambda{=}\\frac12$ shift": [f(base[(ds, D)][7]) for ds in cols],
           "query centroid shift": [f(base[(ds, D)][8]) for ds in cols],
           "Tip-Adapter(-F)": [f(adap[(ds, D)][6]) for ds in cols],
           "CLIP-Adapter, text side": [f(adap[(ds, D)][3]) for ds in cols],
           "CLIP-Adapter, image side": [f(adap[(ds, D)][4]) for ds in cols],
           "CLIP-Adapter, both sides": [f(adap[(ds, D)][5]) for ds in cols]}
    # bold: best gain per column among ours + alternatives
    best = {}
    for j, ds in enumerate(cols):
        cand = {"ours": ours[ds]}
        cand.update({k: v[j] for k, v in alt.items()})
        best[ds] = max(cand, key=cand.get)
    L = [r"\begin{table}[t]", r"\centering", r"\scriptsize", r"\setlength{\tabcolsep}{2.6pt}",
         r"\caption{\textbf{What else could fix it.} Gain in \Rk{50} over the raw",
         r"encoder on the default encoder (" + D + r"), every collection; the top block",
         r"is training-free score corrections, the middle block adapters trained with",
         r"the same recipe and budget as the maps, the bottom block LoRA fine-tuning",
         r"of the encoder on the five collections where it was run (" + LORA_ENC + r",",
         r"one seed; the maps on the same encoder and pairs are shown for comparison).",
         r"Columns sorted by the maps' gain; best gain per column in bold.}", r"\label{tab:alternatives}",
         r"\begin{tabular}{l " + "r" * len(cols) + "}", r"\toprule",
         "& " + " & ".join(cols) + r" \\", r"\midrule",
         row("raw \\Rk{50}", [base[(ds, D)][2] for ds in cols]),
         row(r"\textbf{two linear maps (ours)}", [ours[ds] for ds in cols], bold=[ds for ds in cols if best[ds] == "ours"]),
         r"\midrule"]
    for k, v in list(alt.items())[:5]:
        L.append(row(k, v, bold=[ds for ds in cols if best[ds] == k]))
    L.append(r"\midrule")
    for k, v in list(alt.items())[5:]:
        L.append(row(k, v, bold=[ds for ds in cols if best[ds] == k]))
    L.append(r"\midrule")
    def lr(i, j):
        return [None if ds not in lora else f(lora[ds][i].split("/")[1]) - f(lora[ds][2].split("/")[1]) for ds in cols] if j else \
               [None if ds not in lora else lora[ds][2].split("/")[1] for ds in cols]
    L.append(row(LORA_ENC + ": raw \\Rk{50}", lr(2, False)))
    L.append(row(r"\quad two linear maps", lr(3, True)))
    L.append(row(r"\quad LoRA ($r{=}16$, both towers)", lr(4, True)))
    L.append(row(r"\quad maps on top of LoRA", lr(5, True)))
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (A / "tab_alternatives.tex").write_text("% generated by analysis/make_main_tables.py\n" + "\n".join(L), encoding="utf-8")
    print("[main-tables] ->", A / "tab_grid_main.tex", A / "tab_alternatives.tex")


if __name__ == "__main__":
    main()
